services:
  rag_app:
    build: .
    env_file:
      - .env
    volumes:
      - ./Datos:/app/Datos
      - ./outputs:/app/outputs
    command: [ "python", "main.py" ]

  # Opcional: LLM local, se recomienda para tener modelos de IA en local sin costo alguno
  # Para usarlo: 
  #   1) en .env -> LLM_MODE=local
  #   2) docker compose --profile ollama up --build
  ollama:
    image: ollama/ollama:latest
    profiles: [ "ollama" ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
